Renamed Customer Model with Upper case
semujju/laravel-tutorial pull request #5
Opened 2018-06-04 08:06 UTC by semujju

2018-06-18 10:15 UTC, pirupius requested changes
fix indentation and work on the comments

2018-06-18 10:15 UTC, pirupius commented on app/Customer.php
> +namespace App;
create a new directory called `Models` and add all your models to it

2018-06-18 10:15 UTC, pirupius commented on app/Customer.php
> +}
fix indentation for this file and set it to 4 spaces

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
> +use App\Customer;
make all the necessary changes to your imports so that they reflect the new structure for this case change `use App\Customer;` to `use App\Models\Customer;`

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
>          return view('customers.customerslist',compact('customers'));
it's a good habit to add a space after a comma

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
>          $customer->website        = $request->website;
in cases where the database field name is the same as the form field name, it's just better to auto assign the values 

for example:

       $customer = new Customer($request->all());

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
> +            //$user = User::create(request(['name', 'email', 'password']));
always remember to remove comments that are only vital for ur debug process and development and if u need to use it in the future, always add a todo

for example `//todo chosen: handle logic`

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
> +            return redirect('/customers/register');
look into flashing old input and see if u can play around with it

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
>              //return view('customers.customerform');
remove unnecessary comments and fix indentation

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
> +            return view('customers.customershow',compact('customer'));
indentation :no_entry_sign:

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/CustomersController.php
> +        ]);
create separate request file to validate fields

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/LoanApplicationController.php
> +}
follow the structure and comments i've made on the `CustomersController.php`

2018-06-18 10:15 UTC, pirupius commented on app/Http/Controllers/LoanProductsController.php
> +}
follow the structure and comments i've made on the `CustomersController.php`

2018-06-18 10:15 UTC, pirupius commented on app/LoanApplication.php
> +
remove unnecessary spaces

2018-06-18 10:15 UTC, pirupius commented on app/LoanApplication.php
> +        protected $dates = ['deleted_at'];
indentation :no_entry_sign:

2018-06-18 10:15 UTC, pirupius commented on app/LoanProducts.php
> +namespace App;
move this to `App\Models` directory

2018-06-18 10:15 UTC, pirupius commented on app/LoanProducts.php
> +		protected $dates = ['deleted_at'];
indentation :no_entry_sign:

2018-06-19 13:32 UTC, semujju commented on app/Customer.php
> +namespace App;
done

2018-06-19 13:33 UTC, semujju commented on app/Http/Controllers/CustomersController.php
>          return view('customers.customerslist',compact('customers'));
done

2018-06-19 13:37 UTC, merged

2018-06-21 10:31 UTC, semujju commented on app/Customer.php
> +}
Done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/CustomersController.php
> +use App\Customer;
Done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/CustomersController.php
>          $customer->website        = $request->website;
done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/CustomersController.php
> +            //$user = User::create(request(['name', 'email', 'password']));
Done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/CustomersController.php
>              //return view('customers.customerform');
Done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/CustomersController.php
> +        ]);
done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/LoanApplicationController.php
> +}
done

2018-06-21 10:31 UTC, semujju commented on app/Http/Controllers/LoanProductsController.php
> +}
done

2018-06-21 10:31 UTC, semujju commented on app/LoanApplication.php
> +        protected $dates = ['deleted_at'];
done

2018-06-21 10:31 UTC, semujju commented on app/LoanApplication.php
> +
done

2018-06-21 10:31 UTC, semujju commented on app/LoanProducts.php
> +namespace App;
done

2018-06-21 10:31 UTC, semujju commented on app/LoanProducts.php
> +		protected $dates = ['deleted_at'];
done